### PR TITLE
Create uuidv7.pas

### PR DESCRIPTION
**Pull request by faludiz**
Pascal version of UUIDv7 (only tested in Lazarus and FreePascal)

### CODE REVIEW

**Comment by nalgeon** [comment]
Does not seem to work on [Free Pascal](https://onecompiler.com/pascal/42gdx8ppd):

```text
Free Pascal Compiler version 3.0.4 [2017/10/03] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling main.pas
main.pas(38,3) Error: Identifier not found "Result"
main.pas(47,3) Error: Identifier not found "Result"
main.pas(49,5) Error: Identifier not found "Result"
main.pas(49,14) Error: Identifier not found "Result"
main.pas(50,31) Error: Identifier not found "Result"
main.pas(50,40) Error: Identifier not found "Result"
main.pas(57,4) Fatal: There were 6 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/local/fpc-3.0.4/bin/ppcx64 returned an error exitcode
```

**Comment by faludiz** [comment]
image
it works now ;)
https://onecompiler.com/pascal/42geme6sg

**Comment by nalgeon** [comment]
The random part of the UUID barely changes. Any idea why?

```text
0190234d-1688-7bd8-0190-234d16887bd8
0190234e-9558-7bd8-0190-234e95587bd8
0190234e-b880-7bd8-0190-234eb8807bd8
0190234e-df90-7bd8-0190-234edf907bd8
0190234f-1258-7bd8-0190-234f12587bd8
```

**Comment by faludiz** [comment]
hmmm.... interresting.... i'm used the python code for referrence.... maybe the random generator not enough random?

**Comment by DeveloppeurPascal** [comment]
Hi. A Randomize call should solve the "random is not random in Pascal" problem. ;)

**Comment by nalgeon** [comment]
The lack of `Randomize` is clearly not the only problem. Sorry, I don't have the capacity or Pascal knowledge to investigate further.

**Comment by DeveloppeurPascal** [comment]
Ok, I've tested this code, the randomize was needed, but it gets only the first 64 bits of the generated code. It's can't work as it. Jim's version will be better after his cleaning. https://github.com/nalgeon/uuidv7/pull/5

**Pull request closed without merging**
