### PR TITLE
UUIDv7swift: extend Foundation.UUID with v7 implementation

### PR DESCRIPTION
**Pull request by p16r**

### CODE REVIEW

**Comment by nalgeon** [comment]
Is this really an idiomatic Swift way? It looks worse than the original.

**Comment by p16r** [comment]
Foundation.UUID has an initialiser that takes a 16-tuple of `UInt8`s (https://developer.apple.com/documentation/foundation/uuid/1779900-init). You could still use the array for bit manipulation but it would have to be converted to a tuple to initialise UUID so I chose to work with a 16-tuple directly instead.

**Comment by nalgeon** [comment]
Okay, if you say so 😅 Thanks!

**Comment by p16r** [comment]
Thanks, I appreciate it!

Out of curiosity, what exactly felt non-idiomatic to you?

**Comment by nalgeon** [comment]
This part looks pretty weird to me:

```swift
static func v7() -> Self {
    // random bytes
    var value = (
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255),
        UInt8.random(in: 0...255)
    )
```

It's weird that you can't create a tuple without assigning each of the elements separately. What if I have 1024 of them 😁

**Comment by p16r** [comment]
Ah I see. Swift tuples are very lightweight and ad hoc data structures. There isn't a lot you can do to programmatise tuple generation. Wherever tuple are used it's typical to see 2-tuples only. Even 3- or 4-tuples are rare. This 16-tuple is the edge case-iest of edge cases I've ever seen.

**Pull request merged**
