### PR TITLE
Pascal implementation

### PR DESCRIPTION
**Pull request by jimmckeeth**
with demos in Delphi and Lazarus
Option to use Mormot's secure TAESPRNG instead of the built in RNG

The UUIDv7 implementation is the same between Delphi and Lazarus, but the console application is slightly different, thus the decision to split it into multiple files.

The built in Random routine isn't secure, which is why the optional one was introduced.

### CODE REVIEW

**Comment by nalgeon** [comment]
Sorry, but this is not exactly the expected format. I'm ready to accept a simplified single-file implementation without conditional imports. Given the "no 3rd party dependencies" preference, I'd go with the `Random` option. Or, if it's really that bad, the `mormot` one.

Please leave only a single file `src/uuidv7.pas` with one of the console examples in it.

**Comment by jimmckeeth** [comment]
OK, can do

**Comment by jimmckeeth** [comment]
I put all the sample apps in a `Tests` folder, but those are just for your use if interested. Anyone familiar with either Delphi or FPC will have no issue using the `.pas` file. 

I had the same behavior you mentioned in #3 when the FPC program was ran without a debugger. Not sure why that happens. I mostly use Delphi, and it works fine there.

I modified the .pas file so it can run as a full FreePascal program, or as a normal Unit from a Delphi application. The function code contains no conditional defines.

If you rather I could make a DelphiUUIDv7.pas and FreePlascalUUIDv7.pas

Sample from FPC
{0190280d-7bb7-8003-8641-69ca1bdf7072}
{0190280d-7bb7-800c-8e20-b369b874ec9a}
{0190280d-7bb7-8005-8ecd-84c41e7b2fc9}

Sample from Delphi
{01902811-7fd5-0009-8608-5a427f656bb2}
{01902811-7fd5-000c-8520-5bc6168cbf39}
{01902811-7fd5-0008-8ef2-85ce96fe3d2b}

**Comment by nalgeon** [comment]
I'm sorry, but could you please remove everything but `src/uuidv7.pas` and `README.md` from the pull request? I understand that you want to have a full-blown project with tests and everything, but that's just not what this repo is about.

**Comment by jimmckeeth** [comment]
You should be able to just pull the files you want ... but I can put them in a different branch if that would be easier for you.

**Comment by nalgeon** [comment]
Thank you!

**Comment by jimmckeeth** [comment]
Welcome. I know the chaos that is heading cats in open source development.

**Pull request merged**
