### PR TITLE
No more editor wars! (Emacs Lisp + Vimscript implementation)

### PR DESCRIPTION
**Pull request by pascalecu**

### CODE REVIEW

**Comment by nalgeon** [comment]
Could you please make both versions have actual millisecond precision instead of multiplying seconds by 1000?

**Comment by pascalecu** [comment]
I was able to find a more accurate way within Emacs to get the ms with the precision I needed. The floating point solution was fine too, since it was accurate for my needs, but having an integer is nice as well.

As for Vimscript... yeah, that doesn't work too well. I was considering `strftime`, but it isn't much better than just calling `date`, considering the shell command uses `strftime` under the hood, so I am limited to whatever the system C function allows. So, my approach is to have some common fallbacks that _should_ be good enough. Maybe somebody else can find a better solution and make a PR.

Sidenote: other solutions also multiply the seconds by 1000, so I am not the only one. These should be fine for generating UUIDs.

**Comment by nalgeon** [comment]
Not sure I follow you on the timestamps. The problem is not the multiplication by 1000 per se, it's the lack of millisecond precision.

Could you please generate 5 sample UUIDs (separate for Emacs and Vim) and post them here?

**Comment by pascalecu** [comment]
Keep in mind I am on Linux, so I do have `date +%s%3N` available, which makes the Vim solution output correct UUIDs. The biggest problem here is the BSD family which can't give me perfect millisecond precision, as noted by [the shell solution](https://github.com/nalgeon/uuidv7/blob/main/src/uuidv7.sh).

Emacs:
```
019039493d1d7e30afc978018551a305
019039493d1e7f77b960f6e1ec236508
019039493d1f7711a677ca984b7a0cc5
019039493d20700d92b78863a69732bd
019039493d217cdead961e56735ae999
```

Vim:
```
0190394a7c297897a424beb6f1869196
0190394a7c3c74d1bae73f19a3adbb50
0190394a7c4871699fd34986b03717a4
0190394a7c50775ba05f0638fec67b01
0190394a7c587e53a5fbfa2750a80fde
0190394a7c5f712da95d2b260a1684cc
```

**Comment by nalgeon** [comment]
I see, thank you for explaining!

**Pull request merged**
